### PR TITLE
overpass management:control using thread

### LINKED ISSUE #78: Overpass management
# Problem

Currently, we use the first user attempt to view a campaign as a signal to download data from overpass. Downloading data can take a lot of time causing a bad user experience. We should always serve cached data to the user and update the cache in the background.

# Proposed Solution

Set up a cron that cycles through projects and service the overpass requirements.

### PR DESCRIPTION
**Pull request by meomancer**
this fix #78 
management overpass
- if cache is not exist, get overpass
- if cache is exist but still not expired (15mins), show current data
- if cache is exist but already expired, show current data and fetch overpass by threading

selection_012
selection_013

### CODE REVIEW

**Comment by dimasciput** [comment]
@meomancer could you change the `Data updated...` text color to ```#898989```? Thanks.

**Comment by meomancer** [comment]
Updated

**Comment by dimasciput** [comment]
@meomancer opening existed campaign is working fine, but when I created new campaign this will happen : 

screen shot 2017-06-21 at 11 04 25 am

**Comment by dimasciput** [comment]
LGTM

**Pull request merged**
