### PR TITLE
update add or edit campaign ui

### PR DESCRIPTION
**Pull request by ann26**
Update ui to add/edit campaign

### Create new campaign
screencapture-0-0-0-0-5000-campaign_manager-create-1499428790616
screencapture-0-0-0-0-5000-campaign_manager-create-1499428828902
screencapture-0-0-0-0-5000-campaign_manager-create-1499428843985
screencapture-0-0-0-0-5000-campaign_manager-create-1499428851514
screencapture-0-0-0-0-5000-campaign_manager-create-1499428859626
screencapture-0-0-0-0-5000-campaign_manager-create-1499428873920

### Edit campaign
The difference is in the campaign status and campaign name
screencapture-0-0-0-0-5000-campaign_manager-edit-2644fe29ce86462c9c28d7028e8f8cd8-1499428890539

### CODE REVIEW

**Comment by cchristelis** [comment]
@anne26, plesae refer to the mockups, the  functions, should only be exposed in an advanced mode. The thinking is that the underlying functions are a result of the campaign type selected.

**Comment by ann26** [comment]
ok @cchristelis

**Comment by ann26** [comment]
Hi @cchristelis , could you point me to the mockup please? 
In https://github.com/hotosm/field-campaigner/wiki/Add-edit-campaign-workflow there is no descriptions about advanced settings, only that user is able to add/remove tags.
Also from that page, in the picture under `Create AOI`, the functions were shown although it is in a basic mode.

**Comment by cchristelis** [comment]
@ann26, the only difference at the moment, is that in advanced we also are able to edit insights functions.

**Comment by ann26** [comment]
ok @cchristelis

**Comment by dimasciput** [comment]
Current view :

screen shot 2017-07-10 at 11 42 29 am

Todo : 
- [ ] Update css to supports bigger resolution
- [ ] Add remote mapper

**Pull request merged**
