### PR TITLE
[WIP] download kml instead of just opening maps.me

### LINKED ISSUE #317: Improve Maps.me experience by opening AOI into app
Some feedback from users when using Maps.me after visiting the dashboard page: 

> What did you think you’ll see when you clicked the Maps.me button? 
> 
> The AOI of the campaign open up in Maps.me
Instead it located the Maps.me app in the App Store (using iOS)
Opened Maps.me, but nothing happened

Idea proposed: open a bookmark or KML file directly into Maps.me to show area that should be mapped. This seems to be supported by Maps.me: https://support.maps.me/hc/en-us/articles/207895029-How-can-I-import-bookmarks-

### PR DESCRIPTION
**Pull request by meomancer**
this fix #317 
Progress : 
- geojson converted to kml
- kml is downloaded when maps.me clicked

TODO:
- on android, it doesn't open maps me when click file after download. Need to go explorer first
- testing on iphone

### CODE REVIEW

**Comment by dimasciput** [comment]
Tested on ios : 
img_0410

It doesn't download the file, I'll fix it.

**Comment by cchristelis** [comment]
@ann26 , could you please have a look at this PR.

**Comment by ann26** [comment]
ok @cchristelis

**Comment by meomancer** [comment]
legacy

**Pull request closed without merging**
