### PR TITLE
add date validator

### LINKED ISSUE #158: validate campaign date

### PR DESCRIPTION
**Pull request by ann26**
fix #158 

Start date can be picked until `end date`
screenshot from 2017-07-10 17-17-44

End date can be picked start from `start date`
screenshot from 2017-07-10 17-17-28

note: this PR also change the position of campaign name input in the form

### CODE REVIEW

**Comment by dimasciput** [comment]
Can you also add javascript validation for empty campaign name and date fields when user click the next button? Just to makes sure that everything is in order before it submitted.

**Comment by dimasciput** [comment]
And maybe it was just me, but the date fields is not really clear for user, it doesn't looks like input fields.

screen shot 2017-07-10 at 6 00 59 pm

Any idea @MariaSolovyeva @cchristelis ?

**Comment by ann26** [comment]
ok @dimasciput

**Comment by ann26** [comment]
update name and date validation:
screencapture-0-0-0-0-5000-campaign_manager-create-1499743864066

**Comment by dimasciput** [comment]
@ann26, Did you put first cursor focus on the name field?

**Comment by cchristelis** [comment]
@ann24, please also update how the types are handled, as these aren't
in-line with the mockups yet...

Sincerely,
Christian

------------------------------------------------------------------------------------------
Christian Christelis - Software Engineer
cell: +27 722 667 344
office: +21 880 0990
Skype: christianchristelis
Visit http://kartoza.com to find out about open source:
 * Desktop GIS programming services
 * Geospatial web development
* GIS Training
* Consulting Services
-------------------------------------------------------------------------------------------
Kartoza is a merger between Linfiniti and Afrispatial

**Pull request merged**
