### PR TITLE
[WIP] osmcha update

### LINKED ISSUE #93: Change OSMCHA source to use API
# Problem
Now we are getting dara osmcha from it's dashboard and scrap it's page

# Solution
Use API to get the data
http://osmcha-django-staging.tilestream.net/api-docs/

although it is still in staging

### PR DESCRIPTION
**Pull request by meomancer**
this fix #93 
also it said that on api, we could use geometry

here example that i use
```
'{"type": "FeatureCollection", "features": [{"type": "Feature", "properties": {}, "geometry": {"type": "Polygon", "coordinates": [[[-34.03985816485562,20.429506301879886,], [-34.01510358992117,20.429506301879886], [-34.01510358992117,20.456285476684574], [-34.03985816485562,20.456285476684574], [-34.03985816485562,20.429506301879886]]]}}]}'
```
but it gives empty result.
Maybe my geometry format is not correct?

i use the geometry based on campaign geometry
here is if in bbox
http://osmcha-django-staging.tilestream.net/api/v1/changesets/?page=1&page_size=15&in_bbox=20.429506301879886,-34.03985816485562,20.456285476684574,-34.01510358992117&date__gte=2017-05-01&date__lte=2017-06-02

### CODE REVIEW

**Comment by batpad** [comment]
cc @willemarcel

So I'm pretty sure the `geometry` field requires just a single `geometry` and not a full geojson `Feature`.

Could you try passing in like:
`{"type": "Polygon", "coordinates": [[[-34.03985816485562,20.429506301879886,], [-34.01510358992117,20.429506301879886], [-34.01510358992117,20.456285476684574], [-34.03985816485562,20.456285476684574], [-34.03985816485562,20.429506301879886]]]}}]}`

I'm sure @willemarcel will be able to confirm here.

**Comment by willemarcel** [comment]
@batpad Yes, the geometry field requires a single geometry. The only thing wrong in your example is that there are more closing brackets than needed: `}]}`

**Comment by meomancer** [comment]
Updated:
- Use geometry instead bbox
- Added osmcha feature to show on table

@batpad @willemarcel 
maybe my notes is:
1. when i go to http://osmcha-django-staging.tilestream.net/, and i select one changesets, it says not found. field would like to link the changeset url.
2. It is pretty fast for
```
http://osmcha-django-staging.tilestream.net/api/v1/changesets/?page=1&page_size=15&geometry=%7B%22type%22%3A+%22MultiPolygon%22%2C+%22coordinates%22%3A+%5B%5B%5B%5B20.42787551879883%2C+-34.04071164207856%5D%2C+%5B20.42787551879883%2C+-34.02854878090723%5D%2C+%5B20.444784164428714%2C+-34.02854878090723%5D%2C+%5B20.444784164428714%2C+-34.04071164207856%5D%2C+%5B20.42787551879883%2C+-34.04071164207856%5D%5D%5D%2C+%5B%5B%5B20.4276180267334%2C+-34.02769518131149%5D%2C+%5B20.4276180267334%2C+-34.01673989100637%5D%2C+%5B20.444784164428714%2C+-34.01673989100637%5D%2C+%5B20.444784164428714%2C+-34.02769518131149%5D%2C+%5B20.4276180267334%2C+-34.02769518131149%5D%5D%5D%2C+%5B%5B%5B20.44538497924805%2C+-34.04078276479281%5D%2C+%5B20.44538497924805%2C+-34.01688217656674%5D%2C+%5B20.459547042846683%2C+-34.01688217656674%5D%2C+%5B20.459547042846683%2C+-34.04078276479281%5D%2C+%5B20.44538497924805%2C+-34.04078276479281%5D%5D%5D%5D%7D&date__gte=2017-05-01&date__lte=2017-06-02
```
but when i change to feature, it takes long time
```
http://osmcha-django-staging.tilestream.net/api/v1/features/?page=1&page_size=15&geometry=%7B%22type%22%3A+%22MultiPolygon%22%2C+%22coordinates%22%3A+%5B%5B%5B%5B20.42787551879883%2C+-34.04071164207856%5D%2C+%5B20.42787551879883%2C+-34.02854878090723%5D%2C+%5B20.444784164428714%2C+-34.02854878090723%5D%2C+%5B20.444784164428714%2C+-34.04071164207856%5D%2C+%5B20.42787551879883%2C+-34.04071164207856%5D%5D%5D%2C+%5B%5B%5B20.4276180267334%2C+-34.02769518131149%5D%2C+%5B20.4276180267334%2C+-34.01673989100637%5D%2C+%5B20.444784164428714%2C+-34.01673989100637%5D%2C+%5B20.444784164428714%2C+-34.02769518131149%5D%2C+%5B20.4276180267334%2C+-34.02769518131149%5D%5D%5D%2C+%5B%5B%5B20.44538497924805%2C+-34.04078276479281%5D%2C+%5B20.44538497924805%2C+-34.01688217656674%5D%2C+%5B20.459547042846683%2C+-34.01688217656674%5D%2C+%5B20.459547042846683%2C+-34.04078276479281%5D%2C+%5B20.44538497924805%2C+-34.04078276479281%5D%5D%5D%5D%7D&date__gte=2017-05-01&date__lte=2017-06-02
```

**Comment by batpad** [comment]
> when i go to http://osmcha-django-staging.tilestream.net/, and i select one changesets, it says not found. Field Campaigner would like to link the changeset url.

Yes - we haven't integrated the front-end yet - we are working on this and should have it up on staging in the next days. To link to our current testing frontend you can use this kind of URL for a changeset: https://mapbox.github.io/osmcha-frontend/changesets/49458492

When we integrate the front-end into the Django app, the URL would look like https://osmcha-django-staging.tilestream.net/changesets/3456456 for staging and https://osmcha.mapbox.com/changesets/34534563 for production.

> but when i change to feature, it takes long time

:-( -- unfortunately, our current frontend never does feature lookups and we have not tested that use-case extensively. Thank you for flagging. We will check if there's any quick fixes like missing indexes we can do to improve this in the short term. Generally, we probably do want to implement deleting things that are older than some date, to make the database lighter and some of these more complex searches faster. Will see if @willemarcel has any ideas here.

**Comment by meomancer** [comment]
i think we can merge it
- updated link frontend

**Pull request merged**
