### PR TITLE
added boundary uploader

### LINKED ISSUE #49: Campaign bounds
# Problem

It is difficult to add the correct campaign bounds, let's allow users to upload a SHP file when creating the campaign.

# Proposed Solution

Add an upload SHP file button next to the map.

### PR DESCRIPTION
**Pull request by meomancer**
this fix #49 
before upload
selection_053

after upload
screenshot from 2017-05-29 17 28 00
selection_054

### CODE REVIEW

**Comment by dimasciput** [comment]
Is this happening in campaign creation?

**Comment by meomancer** [comment]
not yet @dimasciput 
it is in detail
let me move it

**Comment by meomancer** [comment]
updated, moving to create/edit page
selection_059
selection_060
selection_061
selection_062
selection_063

**Comment by dimasciput** [comment]
Hi @meomancer, I tested this branch and trying to upload non boundary shapefile 
screen shot 2017-05-31 at 9 29 24 am
Surely I got errors in detail view when in the insight function because it's not a boundary. Is there a function that could prevent this?

**Comment by meomancer** [comment]
@dimasciput updated

**Pull request merged**
