### PR TITLE
add current user as default manager when manager is empty

### LINKED ISSUE #206: Default campaign manager
# Problem
The creator of the campaign is not becoming the default manager when the connection is slow.

# Proposed solution
When creating a campaign and campaign manager is empty, it automatically set the current user as campaign manager.

### PR DESCRIPTION
**Pull request by ann26**
fix #206 

peek 2017-07-20 12-29

### CODE REVIEW

**Comment by cchristelis** [comment]
Hi @ann26, a couple of points: 
- Why do I only see the name when I go next and back? I would expect this name to appear from the get-go. 
- It seems strange to be able to remove the project author from the list of managers? What is the intent of the 'x'?
- Your `Next` and `Prev` buttons seem badly formatted.

**Comment by ann26** [comment]
@cchristelis 
- By default, the creator of the campaign should appear automatically as the campaign manager. The gif just show the scenario when it failed to get the default manager. It failed most likely when the connection is bad. Although this case is rarely happened, I tried to reproduce the error but I couldn't. So when it happened anyway (the manager is empty), it will get the current user again when user click on next button.
- Maybe so that the creator can made this campaign for other user?
- I will fix the button.

**Comment by ann26** [comment]
update:
- [x] remove button is removed from default campaign manager
- [x] fix next and prev buttons

screencapture-0-0-0-0-5000-campaign_manager-edit-de395e2b471946cf9c239f30ef6c460a-1500544682480

**Comment by dimasciput** [comment]
LGTM

**Pull request merged**
