### PR TITLE
change field-campaigner-data as module

### LINKED ISSUE #79: Git vs Git
# Problem

We are currently adding our git code and our git data to the same repository. This will cause problems for users who want to set up the system in different environments. 

# Proposed Solution

Split the data and the code repos.

### PR DESCRIPTION
**Pull request by meomancer**
This fix #79 
- change field-campaigner-data as module to this repo : https://github.com/hotosm/field-campaigner-data
- update code regarding this changes

### CODE REVIEW

**Comment by meomancer** [comment]
hi @cchristelis @smit1678 
travis failed when submodule is executed. we need to add travis in the field-campaigner-data?

**Comment by smit1678** [comment]
@meomancer Done. Travis should now be good to go.

**Comment by cchristelis** [comment]
@meomancer, let's not hard code the data source.

**Comment by meomancer** [comment]
@smit1678 @cchristelis 
updated:
- added `DATA_SOURCE` as a path to data source path on local
- handling if data source is not found or valid.

**Comment by meomancer** [comment]
hi @cchristelis found issue.
if we don't harcoded, i'm not sure how to implement it.
because production is using docker, we need to mount the folder first before able to used.
and this mounting needs to be implemented in compose level

do you have suggestion @cchristelis ?

**Comment by cchristelis** [comment]
@meomancer, let's add a step in the make receipe. If this is not specified, let's promt the user.

**Comment by meomancer** [comment]
hi @cchristelis 
updated
- on top of makefile, there is `CAMPAIGN_DATA` variable
- now when we run the container, if the CAMPAIGN_DATA is empty, it will ask where the folder of data

**Comment by meomancer** [comment]
Found that git isn't working on container
- install git
- setup git global to container

**Comment by meomancer** [comment]
hi @cchristelis 
it seem that it is quite hard to do git automatically (or maybe we could just create commit and let user push manually)
because some keys that is needed to be done first
- need to update git config
- need to copy ssh_keys from local to container

what do you suggest, @cchristelis ? should we copy the ssh_keys?

**Comment by cchristelis** [comment]
@meomancer, we could add the keys to allowed keys on the repository and allow push on that account as well:
screen shot 2017-07-17 at 10 02 33 am

**Comment by meomancer** [comment]
hi @cchristelis 
updated:
when creating container, it will regenerate ssh keys and after registered to deploy keys, git is working
selection_016

now it is using `root` user. maybe need to update it?

**Comment by cchristelis** [comment]
great!

**Comment by cchristelis** [comment]
@meomancer, is this ready to merge? I'd like to get this in so that we don't keep having campaign changes muddy up PRs...

**Pull request merged**
