### PR TITLE
use elipsis to cut the text

### LINKED ISSUE #388: campaign creator text went out from card
In the homepage, when there are a lot of tags, the campaign creator text went out of the card

screenshot from 2017-11-08 15-12-50

### PR DESCRIPTION
**Pull request by ann26**
fix #388 

screenshot from 2017-11-08 16-38-47
screenshot from 2017-11-08 16-39-02

### CODE REVIEW

**Comment by meomancer** [comment]
hi @ann26 
nice work
maybe could you add onhover to text 
so when it is hovered, it will show full length?

**Comment by ann26** [comment]
ok @meomancer

**Comment by ann26** [comment]
@meomancer here is update
screenshot from 2017-11-09 18-35-52

**Comment by cchristelis** [comment]
LGTM

**Pull request merged**
