### PR TITLE
template feature types

### PR DESCRIPTION
**Pull request by Dragneel7**
- Added survey folder containing template feature types for field campaigner.

### CODE REVIEW

**Comment by Dragneel7** [comment]
@pierrealixt I have corrected the issue mentioned in GIF and have rebased the PR.

**Comment by pierrealixt** [comment]
Nice!

It might not be related but I got an error from osmcha_errors.

`"GET /campaign/osmcha_errors_data/81510b0f20d5415abf593975a1ae5466?page_size=100 HTTP/1.1" 500`

```
File "/Users/pea/Documents/CODE/KARTOZA/HOTOSM/field-campaigner/flask_project/campaign_manager/views.py", line 269, in get_osmcha_errors_data
    except Campaign.DoesNotExist:
AttributeError: type object 'Campaign' has no attribute 'DoesNotExist'
```

Is it related?

**Comment by Dragneel7** [comment]
It is not related to this PR. The functions still uses the previous version and doesnot calls campaign from DB. It is minor fix.

**Comment by pierrealixt** [comment]
ok, can you please open an issue on this and fix it asap.

Thank you

**Comment by pierrealixt** [comment]
otherwise, this PR LGTM.

**Pull request merged**
