### PR TITLE
update name of function

### LINKED ISSUE #9: Error check review workflow
From the flagged features using error checking in #7 and #8, enable a workflow to open flagged changesets/features in iD or JOSM to make edits. This isn't just a manager workflow, could be open to anyone participating in the campaign.

### LINKED ISSUE #31: tags/labels
# Problem

We would like to have a quick overview of what this campaign is about.

# Proposed Solution

Allow users to add campaign tags to a campaign. These tags will come from a pre-define list, but for the interim allow users to add any of the following:

- buildings 
- roads
- educational facilities
- points of interest
- health facilities
- boundaries

Campaign managers should be able to add multiple of these.

### LINKED ISSUE #34: English, please.
# Problem 

Currently, the insights functions are being exposed by their name in code. This is not very nice, as this is difficult to read and understand.

# Proposed Solution

Add a method to the insights functions which gives a human readable sentence. This should be shown on the insights function selection drop-down.

### PR DESCRIPTION
**Pull request by meomancer**
This fixes #34 , fixes #31 , fixes #9 

Tags:
selection_037
selection_038
selection_039
selection_040

Function Names:
selection_036
selection_035

### CODE REVIEW

**Comment by meomancer** [comment]
Update:
creating insight to list feature that not complete
id will redirect to osm feature

selection_043
selection_041
selection_042

**Comment by cchristelis** [comment]
@meomancer, I think we should the errors.

**Comment by meomancer** [comment]
merge percentage and detail of completeness
selection_044
selection_045

**Comment by cchristelis** [comment]
@meomancer, could you omit the lines that say "clean".

**Comment by dimasciput** [comment]
LGTM

**Pull request merged**
