### PR TITLE
[wip] add additional text

### LINKED ISSUE #391: Text/documentation additions
Need text addition/improvement in some places:

1. Main text (home page, underneath "Map Campaigner" and above "Active campaigns:"); #360 

2. Short description on http://campaigns.hotosm.org/create

3. On a specific campaign page; some explanation on what you see

4. An "About" page or documentation

### PR DESCRIPTION
**Pull request by ann26**
fix #391 

This PR:
- [x] Add header text
- [x] Add short description on create campaign page
- [x] Add about page and link in navigation panel

home page *updated*:
screenshot from 2017-11-15 16-26-11

create campaign page:
screencapture-0-0-0-0-5000-create-1510656571685

About page
screencapture-0-0-0-0-5000-about-1510657434295

### CODE REVIEW

**Comment by ann26** [comment]
Hi @PaulUithol and @smit1678 , what do you think about this?

**Comment by dimasciput** [comment]
LGTM

**Comment by PaulUithol** [comment]
Thanks - could you point me to the file that has the "About" page? I'd like to add some text there on the other tools in the HOT ecosystem MapCampaigner brings together. With links to their docs etc, try to clarify the workflow

**Comment by ann26** [comment]
hi @PaulUithol , here it is https://github.com/hotosm/field-campaigner/blob/develop/flask_project/campaign_manager/templates/about.html

**Pull request merged**
