### PR TITLE
add aerial map to the list

### LINKED ISSUE #328: Background Map
# Problem

I'm trying to use http://aerial.openstreetmap.org.za/ngi-aerial/ for a campaign background but keep getting stuck on validation issues.

### PR DESCRIPTION
**Pull request by ann26**
fix #328 
peek 2017-09-12 10-39

the aerial imagery url is `http://{s}.aerial.openstreetmap.org.za/ngi-aerial/{z}/{x}/{y}.jpg`

### CODE REVIEW

**Comment by dimasciput** [comment]
You will need https or it won't shows up in the secured site.

**Comment by ann26** [comment]
@dimasciput this aerial map does not support https

**Comment by cchristelis** [comment]
@dimasciput, I don't think that is a problem.

**Comment by dimasciput** [comment]
If the secured sites is not totally necessary then I think this is fine.

**Comment by cchristelis** [comment]
@ann26 and @dimasciput, the only thing that is insecure are the map images, which is fine, since the client will already have them publically available.

**Pull request merged**
