### PR TITLE
Added content to resources.html with dynamic Markdown to HTML conversion

### PR DESCRIPTION
**Pull request by prssanna**
- [x] Added a RESOURCES.md file where new content can be added
- [x] Converted existing resources from Rich Text to Markdown in RESOURCES.md
- [x] Added dynamic conversion of Markdown to HTML using [ShowdownJS](https://github.com/showdownjs/showdown) for RESOURCES.md

I can make minor improvements to the Resources page if needed for things like font size and alignment. It currently works as per the requirements given in #412. 

ssi

### CODE REVIEW

**Comment by smit1678** [comment]
@prssanna Thanks for the pull request, this is a great start and works well. I tested this locally. 

Couple points of feedback to round this out: 

* Let's make the section titles and subtitles as markdown headers
* Can we remove the table of contents? 
* Do we need all the `<br>`? We shouldn't have to add those in with markdown. 
* How can we get the correct styles onto the page? Let's match what we have on the [About page](http://campaigns.hotosm.org/about) right now.

**Comment by prssanna** [comment]
@smit1678 Thanks! I've made the required. Just check if it's okay and let me know if I should change anything else.

**Comment by smit1678** [comment]
@prssanna Excellent. Let's bring the style in line a little bit more: 

* left align the `Resources` title, all caps too
* change MapCampaigner subtitle to Getting Started Creating a Campaign, left align

Other style ideas? We have the text go full width on both the About and Resources page, I wonder if it would be more readable if we reduce the width. Thoughts?

**Comment by prssanna** [comment]
@smit1678 Yes you're right, the text will definitely be more readable if we reduce the width, so I've done that, but I think after implementing this change the `Resources` title looks better centre aligned. Do you agree? If not, I can left align it. I've done the other things you've asked for. 👍🏻

**Comment by smit1678** [comment]
thanks @prssanna, sorry for the delay in reviewing. Width looks nice. 

I suggest we keep both the page title and first heading left aligned since that was how the About page was originally designed: 

map campaigner 2018-03-16 11-25-26

map campaigner 2018-03-16 11-26-28

**Pull request merged**
